//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldOutProduct : Product
    {
        public Nullable<System.DateTime> SellEndDate { get; set; }
    }
}
